name: Deploy Creator

on:
  push:
    paths:
      - 'apps/web/**'
      - 'packages/ui/**'
      - 'packages/db/**'
      - 'packages/store/**'
      - 'packages/tailwind-config/**'
      - 'packages/zodTypes/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH and deploy
      env:
        SSH_PRIVATE_KEY_CREATOR: ${{ secrets.SSH_PRIVATE_KEY_CREATOR }}
      run: |
        echo "$SSH_PRIVATE_KEY_CREATOR" > keyfile
        chmod 600 keyfile
        mkdir -p ~/.ssh
        cp known_hosts_creator ~/.ssh/known_hosts
        ssh -t -i keyfile ubuntu@ec2-34-207-233-48.compute-1.amazonaws.com "sudo bash /home/ubuntu/youtubeCreator/apps/web/deploy.sh"